export const intervalMap = {
  "Cb": {
    "unissono": "Cb",
    "primeira aumentada": "C",
    "segunda menor": "Dbb",
    "segunda maior": "Db",
    "terca menor": "Ebb",
    "terca maior": "Eb",
    "quarta diminuta": "Fbb", //
    "quarta justa": "Fb",
    "quarta aumentada": "F",
    "quinta diminuta": "Gbb",
    "quinta justa": "Gb",
    "quinta aumentada": "", //
    "sexta menor": "Abb", 
    "sexta maior": "Ab",
    "setima diminuta": "Bbbb", //
    "setima menor": "Bbb",
    "setima maior": "Bb",
    "oitava diminuta": "Cbb", 
    "oitava justa": "Cb"
  },
  "C": {
    "unissono": "C",
    "primeira aumentada": "C#",
    "segunda menor": "Db",
    "segunda maior": "D",
    "segunda aumentada": "D#",
    "terca menor": "Eb",
    "terca maior": "E",
    "quarta justa": "F",
    "quarta aumentada": "F#",
    "quinta diminuta": "Gb",
    "quinta justa": "G",
    "quinta aumentada": "G#",
    "sexta menor": "Ab",
    "sexta maior": "A",
    "sexta aumentada": "A#",
    "setima menor": "Bb",
    "setima maior": "B",
    "oitava diminuta": "Cb",
    "oitava justa": "C",
  },
  "C#": {
    "unissono": "C#",
    "segunda diminuta": "Db",
    "segunda menor": "D",
    "segunda maior": "D#",
    "terca diminuta": "Eb",
    "terca menor": "E",
    "terca maior": "E#",
    "quarta diminuta": "F",
    "quarta justa": "F#",
    "quinta duplamente diminuta": "Gb",
    "quinta diminuta": "G", 
    "quinta justa": "G#",
    "sexta diminuta": "Ab",
    "sexta menor": "A",
    "sexta maior": "A#",
    "setima diminuta": "Bb",
    "setima menor": "B",
    "setima maior": "B#", //atenção
    "oitava justa": "C#"
  },
  "Db": {
    "unissono": "Db",
    "primeira aumentada": "D",
    "segunda menor": "Ebb",
    "segunda maior": "Eb",
    "terca menor": "Fb",
    "terca maior": "F",
    "quarta justa": "Gb",
    "quarta aumentada": "G",
    "quinta diminuta": "Abb",
    "quinta justa": "Ab",
    "sexta menor": "Bbb",
    "sexta maior": "Bb",
    "setima menor": "Cb",
    "setima maior": "C",
    "oitava justa": "Db"
  },
  "D": {
    "unissono": "D",
    "primeira aumentada": "D#",
    "segunda menor": "Eb",
    "segunda maior": "E",
    "terca menor": "F",
    "terca maior": "F#",
    "quarta diminuta": "Gb",
    "quarta justa": "G",
    "quarta aumentada": "G#",
    "quinta justa": "A",
    "quinta aumentada": "A#",
    "sexta menor": "Bb",
    "sexta maior": "B",
    "setima diminuta": "Cb",
    "setima menor": "C",
    "setima maior": "C#",
    "oitava diminuta": "Db",
    "oitava justa": "D"
  },
  "D#": {
    "unissono": "D#",
    "segunda diminuta": "Eb",
    "segunda menor": "E",
    "segunda maior": "E#",
    "terca diminuta": "F",
    "terca menor": "F#",
    "terca maior": "F##", //G
    "quarta duplamente diminuta": "Gb",
    "quarta diminuta": "G",
    "quarta justa": "G#",
    "quinta diminuta": "A",
    "quinta justa": "A#",
    "sexta diminuta": "Bb",
    "sexta menor": "B",
    "setima diminuta": "C",
    "setima menor": "C#",
    "setima maior": "C##",
    "oitava justa": "D#"
  },
  "Eb": {
    "unissono": "Eb",
    "primeira aumentada": "E",
    "segunda menor": "Fb",
    "segunda maior": "F",
    "segunda aumentada": "F#",
    "terca menor": "Gb",
    "terca maior": "G",
    "terca aumentada": "G#",
    "quarta justa": "Ab",
    "quarta aumentada": "A",
    "quarta duplamente aumentada": "A#", 
    "quinta justa": "Bb",
    "quinta aumentada": "B",
    "sexta menor": "Cb",
    "sexta maior": "C",
    "sexta aumentada": "C#",
    "setima menor": "Db",
    "setima maior": "D",
    "oitava justa": "Eb"
  },
  "E": {
    "unissono": "E",
    "segunda menor": "F",
    "segunda maior": "F#",
    "terca diminuta": "Gb",
    "terca menor": "G",
    "terca maior": "G#",
    "quarta diminuta": "Ab",
    "quarta justa": "A",
    "quarta aumentada": "A#",
    "quinta diminuta": "Bb",
    "quinta justa": "B",
    "sexta menor": "C",
    "sexta maior": "C#",
    "setima diminuta": "Db",
    "setima menor": "D",
    "setima maior": "D#",
    "oitava justa": "E"
  },
  "F": {
    "unissono": "F",
    "primeira aumentada": "F#",
    "segunda menor": "Gb",
    "segunda maior": "G",
    "segunda aumentada": "G#",
    "terca menor": "Ab",
    "terca maior": "A",
    "terca aumentada": "A#",
    "quarta justa": "Bb",
    "quarta aumentada": "B",
    "quinta justa": "C",
    "quinta aumentada": "C#",
    "sexta menor": "Db",
    "sexta maior": "D",
    "setima menor": "Eb",
    "setima maior": "E",
    "oitava justa": "F"
  },
  "F#": {
    "unissono": "F#",
    "segunda diminuta": "Gb",
    "segunda menor": "G",
    "segunda maior": "G#",
    "terca diminuta": "Ab",
    "terca menor": "A",
    "terca maior": "A#",
    "quarta aumentada": "Bb",
    "quarta justa": "B",
    "quarta aumentada": "C",
    "quinta justa": "C#",
    "sexta diminuta": "Db",
    "sexta menor": "D",
    "sexta maior": "D#",
    "setima diminuta": "Eb",
    "setima menor": "E",
    "setima maior": "E#",
    "oitava justa": "F#"
  },
  "Gb": {
    "unissono": "Gb",
    "primeira aumentada": "G",
    "primeira duplamente aumentada": "G#", 
    "segunda menor": "Abb", //G
    "segunda maior": "Ab",
    "segunda aumentada": "A",
    "segunda duplamente aumentada": "A#",
    "terca menor": "Bbb", //A
    "terca maior": "Bb",
    "quarta justa": "Cb", //B
    "quarta aumentada": "C",
    "quarta duplamente aumentada": "C#",
    "quinta justa": "Db",
    "quinta aumentada": "D",
    "quinta duplamente aumentada": "D#",
    "sexta menor": "Ebb",
    "sexta maior": "Eb",
    "sexta aumentada": "E",
    "setima menor": "Fb",
    "setima maior": "F",
    "setima aumentada": "F#",
    "oitava justa": "Gb"
  },
  "G": {
    "unissono": "G",
    "primeira aumentada": "G#",
    "segunda menor": "Ab",
    "segunda maior": "A",
    "segunda aumentada" : "A#",
    "terca menor": "Bb",
    "terca maior": "B",
    "quarta justa": "C",
    "quarta aumentada": "C#",
    "quinta justa": "D",
    "quinta aumentada": "D#",
    "sexta menor": "Eb",
    "sexta maior": "E",
    "setima menor": "F",
    "setima maior": "F#",
    "oitava diminuta": "Gb",
    "oitava justa": "G"
  },
  "G#": {
    "unissono": "G#",
    "segunda menor diminuta": "Ab",
    "segunda menor": "A",
    "segunda maior": "A#",
    "terca diminuta": "Bb",
    "terca menor": "B",
    "terca maior": "B#",
    "quarta diminuta": "C",
    "quarta justa": "C#",
    "quinta duplamente diminuta": "Db",
    "quinta diminuta": "D",
    "quinta justa": "D#",
    "sexta menor": "E",
    "sexta maior": "E#",
    "setima diminuta": "F",
    "setima menor": "F#",
    "setima maior": "F##", //G
    "oitava justa": "G#"
  },
  "Ab": {
    "unissono": "Ab",
    "segunda menor": "Bbb", // Corrigido para segunda menor
    "segunda maior": "Bb",
    "terca menor": "Cb", // A terca menor de Ab é Cb, não B
    "terca maior": "C",
    "quarta justa": "Db",
    "quarta aumentada": "D",
    "quinta justa": "Eb",
    "sexta menor": "Fb", 
    "sexta maior": "F",
    "setima menor": "Gb",
    "setima maior": "G",
    "oitava justa": "Ab"
  },
  "A": {
    "unissono": "A",
    "segunda menor": "Bb",
    "segunda maior": "B",
    "terca menor": "C",
    "terca maior": "C#",
    "quarta justa": "D",
    "quarta aumentada": "D#",
    "quinta justa": "E",
    "sexta menor": "F",
    "sexta maior": "F#",
    "setima menor": "G",
    "setima maior": "G#",
    "oitava justa": "A"
  },
  "A#": {
    "unissono": "A#",
    "segunda menor": "B",
    "segunda maior": "C",
    "terca menor": "C#",
    "terca maior": "D",
    "quarta justa": "D#",
    "quarta aumentada": "E",
    "quinta justa": "F",
    "sexta menor": "F#",
    "sexta maior": "G",
    "setima menor": "G#",
    "setima maior": "A",
    "oitava justa": "A#"
  },
  "Bb": {
    "unissono": "Bb",
    "segunda menor": "Cb",
    "segunda maior": "C",
    "terca menor": "Db",
    "terca maior": "D",
    "quarta justa": "Eb",
    "quarta aumentada": "E",
    "quinta diminuta": "Fb",
    "quinta justa": "F",
    "sexta menor": "Gb",
    "sexta maior": "G",
    "setima menor": "Ab",
    "setima maior": "A",
    "oitava justa": "Bb"
  },
  "B": {
    "unissono": "B",
    "segunda diminuta": "Cb",
    "segunda menor": "C",
    "segunda maior": "C#",
    "terca menor": "D",
    "terca maior": "D#",
    "quarta justa": "E",
    "quarta aumentada": "E#",
    "quinta diminuta": "F",
    "quinta justa": "F#",
    "sexta menor": "G",
    "sexta maior": "G#",
    "setima menor": "A",
    "setima maior": "A#",
    "oitava justa": "B"
  },
  "B#": {
    "unissono": "B#",
    "segunda diminuta": "C",
    "segunda menor": "C#",
    "segunda maior": "C##",
    "terca menor": "D#",
    "terca maior": "D##",
    "quarta justa": "E#",
    "quarta aumentada": "E##",
    "quinta diminuta": "F#",
    "quinta justa": "F##",
    "sexta menor": "G#",
    "sexta maior": "G##",
    "setima menor": "A#",
    "setima maior": "A##",
    "oitava justa": "B#"
  }
};
