export const intervalMap = {
  "Cb": {
    "unissono": "Cb",
    "primeira aumentada": "C",
    "primeira aumentada dupla": "C#",
    "segunda menor": "Dbb",
    "segunda maior": "Db",
    "terca menor": "Ebb",
    "terca maior": "Eb",
    "quarta diminuta": "Fbb", //
    "quarta justa": "Fb",
    "quarta aumentada": "F",
    "quinta diminuta": "Gbb",
    "quinta justa": "Gb",
    "quinta aumentada": "", //
    "sexta menor": "Abb", 
    "sexta maior": "Ab",
    "setima diminuta": "Bbbb", //
    "setima menor": "Bbb",
    "setima maior": "Bb",
    "oitava diminuta": "Cbb", 
    "oitava justa": "Cb",
    "oitava aumentada": "C",
    "nona menor": "Dbb",
    "nona maior": "Db",
    "decima menor": "Ebb",
    "decima maior": "Eb",
    "decima primeira justa": "Fb", //oitava + quarta
    "decima primeira aumentada": "F" //oitava + quarta
  },
  "C": {
    "unissono": "C",
    "primeira aumentada": "C#",
    "segunda menor": "Db",
    "segunda maior": "D",
    "segunda aumentada": "D#",
    "terca menor": "Eb",
    "terca maior": "E",
    "quarta justa": "F",
    "quarta aumentada": "F#",
    "quinta diminuta": "Gb",
    "quinta justa": "G",
    "quinta aumentada": "G#",
    "sexta menor": "Ab",
    "sexta maior": "A",
    "sexta aumentada": "A#",
    "setima menor": "Bb",
    "setima maior": "B",
    "oitava diminuta": "Cb",
    "oitava justa": "C",
    "nona menor": "Db",
    "nona maior": "D",
    "decima menor": "Eb",
    "decima maior": "E",
    "decima primeira justa": "F", //oitava + quarta
    "decima primeira aumentada": "F#" //oitava + quarta
  },
  "C#": {
    "unissono": "C#",
    "segunda diminuta": "Db",
    "segunda menor": "D",
    "segunda maior": "D#",
    "terca diminuta": "Eb",
    "terca menor": "E",
    "terca maior": "E#",
    "quarta diminuta": "F",
    "quarta justa": "F#",
    "quarta aumentada": "F##",
    "quinta duplamente diminuta": "Gb",
    "quinta diminuta": "G", 
    "quinta justa": "G#",
    "sexta diminuta": "Ab",
    "sexta menor": "A",
    "sexta maior": "A#",
    "setima diminuta": "Bb",
    "setima menor": "B",
    "setima maior": "B#", //atenção
    "oitava diminuta": "C",
    "oitava justa": "C#",
    "nona menor": "D",
    "nona maior": "D#",
    "decima menor": "E",
    "decima maior": "E#",
    "decima primeira justa": "F#", 
    "decima primeira aumentada": "F##"  
  },
  "Db": {
    "unissono": "Db",
    "primeira aumentada": "D",
    "segunda menor": "Ebb",
    "segunda maior": "Eb",
    "terca menor": "Fb",
    "terca maior": "F",
    "quarta justa": "Gb",
    "quarta aumentada": "G",
    "quinta diminuta": "Abb",
    "quinta justa": "Ab",
    "sexta menor": "Bbb",
    "sexta maior": "Bb",
    "setima menor": "Cb",
    "setima maior": "C",
    "oitava justa": "Db",
    "nona menor": "Ebb",
    "nona maior": "Eb",
    "decima menor": "Fb",
    "decima maior": "F",
    "decima primeira justa": "Gb", 
    "decima primeira aumentada": "G"   
  },
  "D": {
    "unissono": "D",
    "primeira aumentada": "D#",
    "segunda menor": "Eb",
    "segunda maior": "E",
    "terca menor": "F",
    "terca maior": "F#",
    "quarta diminuta": "Gb",
    "quarta justa": "G",
    "quarta aumentada": "G#",
    "quinta justa": "A",
    "quinta aumentada": "A#",
    "sexta menor": "Bb",
    "sexta maior": "B",
    "setima diminuta": "Cb",
    "setima menor": "C",
    "setima maior": "C#",
    "oitava diminuta": "Db",
    "oitava justa": "D",
    "nona menor": "Eb",
    "nona maior": "E",
    "decima menor": "F",
    "decima maior": "F#",
    "decima primeira justa": "G", 
    "decima primeira aumentada": "G#"   
  },
  "D#": {
    "unissono": "D#",
    "segunda diminuta": "Eb",
    "segunda menor": "E",
    "segunda maior": "E#",
    "terca diminuta": "F",
    "terca menor": "F#",
    "terca maior": "F##", //G
    "quarta duplamente diminuta": "Gb",
    "quarta diminuta": "G",
    "quarta justa": "G#",
    "quarta aumentada": "G##",
    "quinta diminuta": "A",
    "quinta justa": "A#",
    "sexta diminuta": "Bb",
    "sexta menor": "B",
    "setima diminuta": "C",
    "setima menor": "C#",
    "setima maior": "C##",
    "oitava justa": "D#",
    "nona menor": "E",
    "nona maior": "E#",
    "decima menor": "F#",
    "decima maior": "F##",
    "decima primeira justa": "G#", 
    "decima primeira aumentada": "G##"  
  },
  "Eb": {
    "unissono": "Eb",
    "primeira aumentada": "E",
    "segunda menor": "Fb",
    "segunda maior": "F",
    "segunda aumentada": "F#",
    "terca menor": "Gb",
    "terca maior": "G",
    "terca aumentada": "G#",
    "quarta justa": "Ab",
    "quarta aumentada": "A",
    "quarta duplamente aumentada": "A#", 
    "quinta justa": "Bb",
    "quinta aumentada": "B",
    "sexta menor": "Cb",
    "sexta maior": "C",
    "sexta aumentada": "C#",
    "setima menor": "Db",
    "setima maior": "D",
    "oitava justa": "Eb",
    "nona menor": "Fb",
    "nona maior": "F",
    "decima menor": "Gb",
    "decima maior": "G",
    "decima primeira justa": "Ab", 
    "decima primeira aumentada": "A" 
  },
  "E": {
    "unissono": "E",
    "segunda menor": "F",
    "segunda maior": "F#",
    "terca diminuta": "Gb",
    "terca menor": "G",
    "terca maior": "G#",
    "quarta diminuta": "Ab",
    "quarta justa": "A",
    "quarta aumentada": "A#",
    "quinta diminuta": "Bb",
    "quinta justa": "B",
    "sexta menor": "C",
    "sexta maior": "C#",
    "setima diminuta": "Db",
    "setima menor": "D",
    "setima maior": "D#",
    "oitava justa": "E",
    "nona menor": "F",
    "nona maior": "F#",
    "decima menor": "G",
    "decima maior": "G#",
    "decima primeira justa": "A", 
    "decima primeira aumentada": "A#" 
  },
  "F": {
    "unissono": "F",
    "primeira aumentada": "F#",
    "segunda menor": "Gb",
    "segunda maior": "G",
    "segunda aumentada": "G#",
    "terca menor": "Ab",
    "terca maior": "A",
    "terca aumentada": "A#",
    "quarta justa": "Bb",
    "quarta aumentada": "B",
    "quinta justa": "C",
    "quinta aumentada": "C#",
    "sexta menor": "Db",
    "sexta maior": "D",
    "setima menor": "Eb",
    "setima maior": "E",
    "oitava justa": "F",
    "nona menor": "Gb",
    "nona maior": "G",
    "decima menor": "Ab",
    "decima maior": "A",
    "decima primeira justa": "Bb", 
    "decima primeira aumentada": "B" 
  },
  "F#": {
    "unissono": "F#",
    "segunda diminuta": "Gb",
    "segunda menor": "G",
    "segunda maior": "G#",
    "terca diminuta": "Ab",
    "terca menor": "A",
    "terca maior": "A#",
    "quarta justa": "B",
    "quarta aumentada": "B#",
    "quinta diminuta": "C",
    "quinta justa": "C#",
    "sexta diminuta": "Db",
    "sexta menor": "D",
    "sexta maior": "D#",
    "setima diminuta": "Eb",
    "setima menor": "E",
    "setima maior": "E#",
    "oitava justa": "F#",
    "nona menor": "G",
    "nona maior": "G#",
    "decima menor": "A",
    "decima maior": "A#",
    "decima primeira justa": "B", 
    "decima primeira aumentada": "B#" 
  },
  "Gb": {
    "unissono": "Gb",
    "primeira aumentada": "G",
    "primeira duplamente aumentada": "G#", 
    "segunda menor": "Abb", //G
    "segunda maior": "Ab",
    "segunda aumentada": "A",
    "segunda duplamente aumentada": "A#",
    "terca menor": "Bbb", //A
    "terca maior": "Bb",
    "quarta justa": "Cb", //B
    "quarta aumentada": "C",
    "quarta duplamente aumentada": "C#",
    "quinta justa": "Db",
    "quinta aumentada": "D",
    "quinta duplamente aumentada": "D#",
    "sexta menor": "Ebb",
    "sexta maior": "Eb",
    "sexta aumentada": "E",
    "setima menor": "Fb",
    "setima maior": "F",
    "setima aumentada": "F#",
    "oitava justa": "Gb",
    "nona menor": "Abb",
    "nona maior": "Ab",
    "decima menor": "Bbb",
    "decima maior": "Bb",
    "decima primeira justa": "Cb", 
    "decima primeira aumentada": "C"
  },
  "G": {
    "unissono": "G",
    "primeira aumentada": "G#",
    "segunda menor": "Ab",
    "segunda maior": "A",
    "segunda aumentada" : "A#",
    "terca menor": "Bb",
    "terca maior": "B",
    "quarta justa": "C",
    "quarta aumentada": "C#",
    "quinta justa": "D",
    "quinta aumentada": "D#",
    "sexta menor": "Eb",
    "sexta maior": "E",
    "setima menor": "F",
    "setima maior": "F#",
    "oitava diminuta": "Gb",
    "oitava justa": "G",
    "nona menor": "Ab",
    "nona maior": "A",
    "decima menor": "Bb",
    "decima maior": "B",
    "decima primeira justa": "C", 
    "decima primeira aumentada": "C#"
  },
  "G#": {
    "unissono": "G#",
    "segunda menor diminuta": "Ab",
    "segunda menor": "A",
    "segunda maior": "A#",
    "terca diminuta": "Bb",
    "terca menor": "B",
    "terca maior": "B#",
    "quarta diminuta": "C",
    "quarta justa": "C#",
    "quarta aumentada": "C##",
    "quinta duplamente diminuta": "Db",
    "quinta diminuta": "D",
    "quinta justa": "D#",
    "sexta menor": "E",
    "sexta maior": "E#",
    "setima diminuta": "F",
    "setima menor": "F#",
    "setima maior": "F##", //G
    "oitava justa": "G#",
    "nona menor": "A",
    "nona maior": "A#",
    "decima menor": "B",
    "decima maior": "B#",
    "decima primeira justa": "C#", 
    "decima primeira aumentada": "C##"

  },
  "Ab": {
    "unissono": "Ab",
    "segunda menor": "Bbb", // Corrigido para segunda menor
    "segunda maior": "Bb",
    "terca menor": "Cb", // A terca menor de Ab é Cb, não B
    "terca maior": "C",
    "quarta justa": "Db",
    "quarta aumentada": "D",
    "quinta justa": "Eb",
    "sexta menor": "Fb", 
    "sexta maior": "F",
    "setima menor": "Gb",
    "setima maior": "G",
    "oitava justa": "Ab",
    "nona menor": "Bbb",
    "nona maior": "Bb",
    "decima menor": "Cb",
    "decima maior": "C",
    "decima primeira justa": "Db", 
    "decima primeira aumentada": "D"
  },
  "A": {
    "unissono": "A",
    "segunda menor": "Bb",
    "segunda maior": "B",
    "terca menor": "C",
    "terca maior": "C#",
    "quarta diminuta": "Db",
    "quarta justa": "D",
    "quarta aumentada": "D#",
    "quinta justa": "E",
    "sexta menor": "F",
    "sexta maior": "F#",
    "setima menor": "G",
    "setima maior": "G#",
    "oitava justa": "A",
    "nona menor": "Bb",
    "nona maior": "B",
    "decima menor": "C",
    "decima maior": "C#",
    "decima primeira justa": "D", 
    "decima primeira aumentada": "D#" 
  },
  "A#": {
    "unissono": "A#",
    "segunda menor": "B",
    "segunda maior": "B#",
    "terca diminuta": "C",
    "terca menor": "C#",
    "terca maior": "C##",
    "quarta diminuta": "D",
    "quarta justa": "D#",
    "quarta aumentada": "D##",
    "quinta justa": "E",
    "sexta menor": "F",
    "sexta maior": "F#",
    "setima menor": "G",
    "setima maior": "G#",
    "oitava diminuta": "A",
    "oitava justa": "A#",
    "nona menor": "B",
    "nona maior": "B#",
    "decima menor": "C",
    "decima maior": "C#",
    "decima primeira justa": "D", 
    "decima primeira aumentada": "D#" 
  },
  "Bb": {
    "unissono": "Bb",
    "segunda menor": "Cb",
    "segunda maior": "C",
    "terca menor": "Db",
    "terca maior": "D",
    "quarta justa": "Eb",
    "quarta aumentada": "E",
    "quinta diminuta": "Fb",
    "quinta justa": "F",
    "sexta menor": "Gb",
    "sexta maior": "G",
    "setima menor": "Ab",
    "setima maior": "A",
    "oitava justa": "Bb",
    "nona menor": "Cb",
    "nona maior": "C",
    "decima menor": "Db",
    "decima maior": "D",
    "decima aumentada": "D#",
    "decima primeira justa": "Eb", 
    "decima primeira aumentada": "E"  
  },
  "B": {
    "unissono": "B",
    "segunda diminuta": "Cb",
    "segunda menor": "C",
    "segunda maior": "C#",
    "terca menor": "D",
    "terca maior": "D#",
    "quarta justa": "E",
    "quarta aumentada": "E#",
    "quinta diminuta": "F",
    "quinta justa": "F#",
    "sexta menor": "G",
    "sexta maior": "G#",
    "setima menor": "A",
    "setima maior": "A#",
    "oitava justa": "B",
    "nona menor": "C",
    "nona maior": "C#",
    "decima menor": "D",
    "decima maior": "D#",
    "decima primeira justa": "E", 
    "decima primeira aumentada": "E#"   
  },
  "B#": {
    "unissono": "B#",
    "segunda diminuta": "C",
    "segunda menor": "C#",
    "segunda maior": "C##",
    "terca menor": "D#",
    "terca maior": "D##",
    "quarta justa": "E#",
    "quarta aumentada": "E##",
    "quinta diminuta": "F#",
    "quinta justa": "F##",
    "sexta menor": "G#",
    "sexta maior": "G##",
    "setima menor": "A#",
    "setima maior": "A##",
    "oitava justa": "B#",
    "nona menor": "C#",
    "nona maior": "C##",
    "decima menor": "D#",
    "decima maior": "D##",
    "decima primeira justa": "E#", 
    "decima primeira aumentada": "E##"   
  }
};
