type IntervalMap = {
  [key: string]: {
    [key: string]: string;
  };
};

export const intervalMap: IntervalMap = {
  "Cb": {
    "unissono": "Cb",
    "primeira aumentada": "C",
    "primeira aumentada dupla": "C#",
    "segunda menor": "Dbb",
    "segunda maior": "Db",
    "terca menor": "Ebb",
    "terca maior": "Eb",
    "quarta diminuta": "Fbb",
    "quarta justa": "Fb",
    "quarta aumentada": "F",
    "quinta diminuta": "Gbb",
    "quinta justa": "Gb",
    "quinta aumentada": "",
    "sexta menor": "Abb",
    "sexta maior": "Ab",
    "setima diminuta": "Bbbb",
    "setima menor": "Bbb",
    "setima maior": "Bb",
    "oitava diminuta": "Cbb",
    "oitava justa": "Cb",
    "oitava aumentada": "C",
    "nona menor": "Dbb",
    "nona maior": "Db",
    "decima menor": "Ebb",
    "decima maior": "Eb",
    "decima primeira justa": "Fb",
    "decima primeira aumentada": "F"
  },
  "C": {
    "unissono": "C",
    "primeira aumentada": "C#",
    "segunda menor": "Db",
    "segunda maior": "D",
    "segunda aumentada": "D#",
    "terca menor": "Eb",
    "terca maior": "E",
    "quarta justa": "F",
    "quarta aumentada": "F#",
    "quinta diminuta": "Gb",
    "quinta justa": "G",
    "quinta aumentada": "G#",
    "sexta menor": "Ab",
    "sexta maior": "A",
    "sexta aumentada": "A#",
    "setima menor": "Bb",
    "setima maior": "B",
    "oitava diminuta": "Cb",
    "oitava justa": "C",
    "nona menor": "Db",
    "nona maior": "D",
    "decima menor": "Eb",
    "decima maior": "E",
    "decima primeira justa": "F",
    "decima primeira aumentada": "F#"
  },
  "C#": {
    "unissono": "C#",
    "segunda diminuta": "Db",
    "segunda menor": "D",
    "segunda maior": "D#",
    "terca diminuta": "Eb",
    "terca menor": "E",
    "terca maior": "E#",
    "quarta diminuta": "F",
    "quarta justa": "F#",
    "quarta aumentada": "F##",
    "quinta duplamente diminuta": "Gb",
    "quinta diminuta": "G",
    "quinta justa": "G#",
    "sexta diminuta": "Ab",
    "sexta menor": "A",
    "sexta maior": "A#",
    "setima diminuta": "Bb",
    "setima menor": "B",
    "setima maior": "B#",
    "oitava diminuta": "C",
    "oitava justa": "C#",
    "nona menor": "D",
    "nona maior": "D#",
    "decima menor": "E",
    "decima maior": "E#",
    "decima primeira justa": "F#",
    "decima primeira aumentada": "F##"
  },
  "Db": {
    "unissono": "Db",
    "primeira aumentada": "D",
    "segunda menor": "Ebb",
    "segunda maior": "Eb",
    "terca menor": "Fb",
    "terca maior": "F",
    "quarta justa": "Gb",
    "quarta aumentada": "G",
    "quinta diminuta": "Abb",
    "quinta justa": "Ab",
    "sexta menor": "Bbb",
    "sexta maior": "Bb",
    "setima menor": "Cb",
    "setima maior": "C",
    "oitava justa": "Db",
    "nona menor": "Ebb",
    "nona maior": "Eb",
    "decima menor": "Fb",
    "decima maior": "F",
    "decima primeira justa": "Gb",
    "decima primeira aumentada": "G"
  },
  "D": {
    "unissono": "D",
    "primeira aumentada": "D#",
    "segunda menor": "Eb",
    "segunda maior": "E",
    "terca menor": "F",
    "terca maior": "F#",
    "quarta diminuta": "Gb",
    "quarta justa": "G",
    "quarta aumentada": "G#",
    "quinta justa": "A",
    "quinta aumentada": "A#",
    "sexta menor": "Bb",
    "sexta maior": "B",
    "setima diminuta": "Cb",
    "setima menor": "C",
    "setima maior": "C#",
    "oitava diminuta": "Db",
    "oitava justa": "D",
    "nona menor": "Eb",
    "nona maior": "E",
    "decima menor": "F",
    "decima maior": "F#",
    "decima primeira justa": "G",
    "decima primeira aumentada": "G#"
  },
  "D#": {
    "unissono": "D#",
    "segunda diminuta": "Eb",
    "segunda menor": "E",
    "segunda maior": "E#",
    "terca diminuta": "F",
    "terca menor": "F#",
    "terca maior": "F##",
    "quarta duplamente diminuta": "Gb",
    "quarta diminuta": "G",
    "quarta justa": "G#",
    "quarta aumentada": "G##",
    "quinta diminuta": "A",
    "quinta justa": "A#",
    "sexta diminuta": "Bb",
    "sexta menor": "B",
    "setima diminuta": "C",
    "setima menor": "C#",
    "setima maior": "C##",
    "oitava justa": "D#",
    "nona menor": "E",
    "nona maior": "E#",
    "decima menor": "F#",
    "decima maior": "F##",
    "decima primeira justa": "G#",
    "decima primeira aumentada": "G##"
  },
  "Eb": {
    "unissono": "Eb",
    "primeira aumentada": "E",
    "segunda menor": "Fb",
    "segunda maior": "F",
    "segunda aumentada": "F#",
    "terca menor": "Gb",
    "terca maior": "G",
    "terca aumentada": "G#",
    "quarta justa": "Ab",
    "quarta aumentada": "A",
    "quarta duplamente aumentada": "A#",
    "quinta justa": "Bb",
    "quinta aumentada": "B",
    "sexta menor": "Cb",
    "sexta maior": "C",
    "sexta aumentada": "C#",
    "setima menor": "Db",
    "setima maior": "D",
    "oitava justa": "Eb",
    "nona menor": "Fb",
    "nona maior": "F",
    "decima menor": "Gb",
    "decima maior": "G",
    "decima primeira justa": "Ab",
    "decima primeira aumentada": "A"
  },
  "E": {
    "unissono": "E",
    "segunda menor": "F",
    "segunda maior": "F#",
    "terca diminuta": "Gb",
    "terca menor": "G",
    "terca maior": "G#",
    "quarta diminuta": "Ab",
    "quarta justa": "A",
    "quarta aumentada": "A#",
    "quinta diminuta": "Bb",
    "quinta justa": "B",
    "sexta menor": "C",
    "sexta maior": "C#",
    "setima diminuta": "Db",
    "setima menor": "D",
    "setima maior": "D#",
    "oitava justa": "E",
    "nona menor": "F",
    "nona maior": "F#",
    "decima menor": "G",
    "decima maior": "G#",
    "decima primeira justa": "A",
    "decima primeira aumentada": "A#"
  },
  "F": {
    "unissono": "F",
    "primeira aumentada": "F#",
    "segunda menor": "Gb",
    "segunda maior": "G",
    "segunda aumentada": "G#",
    "terca menor": "Ab",
    "terca maior": "A",
    "terca aumentada": "A#",
    "quarta justa": "Bb",
    "quarta aumentada": "B",
    "quinta justa": "C",
    "quinta aumentada": "C#",
    "sexta menor": "Db",
    "sexta maior": "D",
    "setima menor": "Eb",
    "setima maior": "E",
    "oitava justa": "F",
    "nona menor": "Gb",
    "nona maior": "G",
    "decima menor": "Ab",
    "decima maior": "A",
    "decima primeira justa": "Bb",
    "decima primeira aumentada": "B"
  },
  "F#": {
    "unissono": "F#",
    "segunda diminuta": "Gb",
    "segunda menor": "G",
    "segunda maior": "G#",
    "terca diminuta": "Ab",
    "terca menor": "A",
    "terca maior": "A#",
    "quarta justa": "B",
    "quarta aumentada": "B#",
    "quinta diminuta": "C",
    "quinta justa": "C#",
    "sexta menor": "D",
    "sexta maior": "D#",
    "setima diminuta": "Eb",
    "setima menor": "E",
    "setima maior": "E#",
    "oitava justa": "F#",
    "nona menor": "G",
    "nona maior": "G#",
    "decima menor": "A",
    "decima maior": "A#",
    "decima primeira justa": "B",
    "decima primeira aumentada": "B#"
  }
}; 